first commit
VladKvetkin/gophkeeper pull request #1
Opened 2023-12-05 07:35 UTC by VladKvetkin

Можешь меня поздравить, устроился на свою первую работу Go-разработчиком :) Времени на обучение критически мало, постараюсь на выходных сделать базовый функционал и тогда можно проверять. Сейчас отправил, чтобы успеть в дедлайн :)

2023-12-06 17:20 UTC, valentinsoe requested changes
Привет!
Во-первых поздравляю, это здорово!
Во-вторых я тут сам в феерической запаре и нормально бы проверить диплом не смог, мне сейчас только на руку:)

2023-12-12 15:08 UTC, VladKvetkin commented
Привет. Отправил проект, сделал минимум. Прошу принять, т.к. времени на доработку в этом году уже не будет, сейчас полностью на новом месте, погружаюсь в работу :)

2023-12-18 06:15 UTC, valentinsoe approved these changes
Привет. Извиняюсь за задержку проверки.
По самому коду у меня в целом претензий нет.  Отлично, что написаны тесты и комментарии.
Что сделано не очень удачно:
1) данные в БД лежат в открытом виде. Укравший бекап твоей БД получит доступ ко всем секретам всех пользователей.
2) работа с файлами
2.1) Их не стоит писать в JSON и выводить обратно пользователю. Там могут быть недопустимые символы
2.2 ) Их не стоит сохранять в БД
3) Интерфейс пользователя.

Чего не хватает из задания?
Нет метаданных у секретов.

2023-12-18 06:15 UTC, valentinsoe commented on internal/client/app/get_user_data.go
> +		err := easyjson.Unmarshal(data.Data, file)
С файлом так работать не будет. Он же может быть бинарным.
По-хорошему надо спрашивать у пользователя куда его сохранить.

2023-12-18 07:33 UTC, merged